### ISSUE TITLE
Pagarme Javascript StyleGuide

### ISSUE THREAD

**Issue by mccraveiro** [pagarme/react-style-guide#2]
Shouldn't this project extends [pagarme/javascript-style-guide](https://github.com/pagarme/javascript-style-guide)?

**Comment by derekstavis** [comment]
Definitely! The only issue is that AirBnb has separate packages (`eslint-config-airbnb-base` and `eslint-config-airbnb`). As I didn't knew how extending both packages would work, I just went with copypasta!
